version: "3.8"
services:

  spring:
    build:
      context: .
    container_name: spring
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ist
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s